apiVersion: v1
kind: Service
metadata:
  name: myproject
spec:
  selector:
    app: myproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
  type: NodePort
